apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "redwine1"
  namespace: kserve-inference
spec:
  predictor:
    serviceAccountName: kserve-sa 
    model:
      modelFormat: 
        name: sklearn
      storageUri: s3://mlflow/49/56acb756eede4b05850f96ad0c5efde5/artifacts/wine-quality # change to the S3 URI of your model artifact
---
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "redwine2"
  namespace: kserve-inference
spec:
  predictor:
    serviceAccountName: kserve-sa 
    model:
      modelFormat: 
        name: sklearn
      storageUri: s3://mlflow/49/bb610e857a3342bdbf87cd4dee4843c8/artifacts/wine-quality # change to the S3 URI of your model artifact