name: mlops_eng2_t1
channels:
  - conda-forge
  - defaults
dependencies:
  # Python 3.11，适配 macOS arm64 平台
  - python=3.10
  # 常用基础包
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - xgboost
  - lightgbm
  # 工具包
  - pip
  - poetry
  - jupyterlab
  - ipywidgets
  # 安全和认证相关
  - openssl
  - cffi
  - cryptography
  # 系统工具
  - libiconv
  - readline
  - zlib
  - sqlite
  # pip 额外依赖包（包含 ray）
  - pip:
      - aiofiles==23.2.1
      - aiohttp==3.9.3
      - aiohttp-cors==0.7.0
      - aiokafka==0.10.0
      - aiorwlock==1.4.0
      - aiosignal==1.3.1
      - alembic==1.13.1
      - anyio==4.3.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asgiref==3.7.2
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.2.0
      - babel==2.14.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - blessed==1.20.0
      - blinker==1.7.0
      - boto3==1.34.62
      - botocore==1.34.62
      - brotli==1.1.0
      - cachetools==5.3.3
      - click==8.1.7
      - cloudevents==1.10.1
      - cloudpickle==3.0.0
      - colorful==0.5.6
      - colorlog==6.8.2
      - comm==0.2.2
      - contourpy==1.2.0
      - cycler==0.12.1
      - databricks-cli==0.18.0
      - debugpy==1.8.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - deprecated==1.2.14
      - deprecation==2.1.0
      - docker==6.1.3
      - docstring-parser==0.15
      - entrypoints==0.4
      - executing==2.0.1
      - fastapi==0.95.2
      - filelock==3.13.1
      - flask==3.0.2
      - fonttools==4.49.0
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - gevent==24.2.1
      - geventhttpclient==2.0.2
      - gitdb==4.0.11
      - gitpython==3.1.42
      - google-api-core==2.17.1
      - google-auth==2.28.2
      - google-cloud-core==2.4.1
      - google-cloud-storage==2.15.0
      - google-crc32c==1.5.0
      - google-resumable-media==2.7.0
      - googleapis-common-protos==1.63.0
      - gpustat==1.1.1
      - greenlet==3.0.3
      - grpcio==1.62.1
      - gunicorn==21.2.0
      - h11==0.14.0
      - httpcore==1.0.4
      - httptools==0.6.1
      - httpx==0.26.0
      - importlib-metadata==6.11.0
      - importlib-resources==5.13.0
      - iniconfig==2.0.0
      - ipykernel==6.29.3
      - ipython==8.22.2
      - ipywidgets==8.1.2
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jedi==0.19.1
      - jinja2==3.1.3
      - jmespath==1.0.1
      - joblib==1.3.2
      - json5==0.9.22
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - jupyter-events==0.9.1
      - jupyter-lsp==2.2.4
      - jupyter-server==2.13.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.1.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.4
      - jupyterlab-widgets==3.0.10
      - kfp==2.0.1
      - kfp-kubernetes==1.0.0
      - kfp-pipeline-spec==0.2.2
      - kfp-server-api==2.0.5
      - kiwisolver==1.4.5
      - kserve==0.12.0
      - kubernetes==26.1.0
      - lightgbm==3.3.5
      - mako==1.3.2
      - markdown==3.5.2
      - markupsafe==2.1.5
      - matplotlib==3.8.3
      - matplotlib-inline==0.1.6
      - minio==7.1.3
      - mistune==3.0.2
      - mlflow==2.9.2
      - mlserver==1.4.0
      - mlserver-mlflow==1.4.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - nbclient==0.10.0
      - nbconvert==7.16.2
      - nbformat==5.10.2
      - nbgrader==0.9.1
      - nest-asyncio==1.6.0
      - notebook==7.1.1
      - notebook-shim==0.2.4
      - nvidia-ml-py==12.535.133
      - oauthlib==3.2.2
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opentelemetry-api==1.23.0
      - opentelemetry-exporter-otlp-proto-common==1.23.0
      - opentelemetry-exporter-otlp-proto-grpc==1.23.0
      - opentelemetry-instrumentation==0.44b0
      - opentelemetry-instrumentation-asgi==0.44b0
      - opentelemetry-instrumentation-fastapi==0.44b0
      - opentelemetry-instrumentation-grpc==0.44b0
      - opentelemetry-proto==1.23.0
      - opentelemetry-sdk==1.23.0
      - opentelemetry-semantic-conventions==0.44b0
      - opentelemetry-util-http==0.44b0
      - optuna==3.5.0
      - orjson==3.9.15
      - overrides==7.7.0
      - packaging==23.2
      - pandas==2.2.1
      - pandocfilters==1.5.1
      - parso==0.8.3
      - pillow==10.2.0
      - pluggy==1.4.0
      - prometheus-client==0.13.1
      - prompt-toolkit==3.0.43
      - protobuf==3.20.3
      - psutil==5.9.8
      - pure-eval==0.2.2
      - py-grpc-prometheus==0.8.0
      - py-spy==0.3.14
      - pyarrow==14.0.2
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pydantic==1.10.14
      - pygments==2.17.2
      - pyjwt==2.8.0
      - pyparsing==3.1.2
      - pytest==8.1.1
      - pytest-timeout==2.3.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-json-logger==2.0.7
      - python-rapidjson==1.16
      - pytz==2023.4
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - querystring-parser==1.2.4
      - rapidfuzz==3.6.2
      - ray==2.9.3
      - referencing==0.33.0
      - requests-oauthlib==1.4.0
      - requests-toolbelt==0.10.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.18.0
      - rsa==4.9
      - s3transfer==0.10.0
      - scikit-learn==1.4.1.post1
      - scipy==1.12.0
      - send2trash==1.8.2
      - setuptools==69.2.0
      - six==1.16.0
      - smart-open==7.0.1
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.5
      - sqlalchemy==2.0.28
      - sqlparse==0.4.4
      - stack-data==0.6.3
      - starlette==0.27.0
      - starlette-exporter==0.17.1
      - tabulate==0.9.0
      - terminado==0.18.1
      - threadpoolctl==3.3.0
      - timing-asgi==0.3.1
      - tinycss2==1.2.1
      - tornado==6.4
      - tqdm==4.66.2
      - traitlets==5.14.2
      - tritonclient==2.41.1
      - types-python-dateutil==2.8.19.20240311
      - typing-extensions==4.10.0
      - tzdata==2024.1
      - uri-template==1.3.0
      - urllib3==1.26.18
      - uvicorn==0.19.0
      - uvloop==0.19.0
      - watchfiles==0.21.0
      - wcwidth==0.2.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - websockets==12.0
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.10
      - wrapt==1.16.0
      - xgboost==2.0.3
      - yarl==1.9.4
      - zipp==3.18.0
      - zope-event==5.0
      - zope-interface==6.2

